title: Dhananjaya BL
logo: /assets/img/logo.png
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/dhananjayabl/">LinkedIn</a>
  
  <br>
  I'm working on Data Science, Machine Learning, Computer Vission based solutions for HealthCare domain.
  Currently working for NEC Laboratories India, previously worked for SolverMinds Technologies and TechMahindra. 
  Working in Data Science for 5 years.
  <br>
  </p>
theme: jekyll-theme-minimal
